name: SpaceMining-Train-Upload
on:
  push:
    branches: [ master ]
  workflow_dispatch:

# 自动化执行任务
jobs:
  deploy:
    runs-on: ubuntu-latest
    # 传入Hugging Face密钥
    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}
      HF_USERNAME: ${{ secrets.HF_USERNAME }}
    steps:
      # 拉取GitHub代码
      - name: Pull Code
        uses: actions/checkout@v4
      
      # 配置Python环境
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      
      # 安装项目依赖
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # 运行训练脚本
      - name: Train Model
        run: python train.py
      
      # 上传模型至Hugging Face
      - name: Upload to HuggingFace
        run: python upload_hf.py